version: '3'

networks: 
    laravelnet:
        driver: bridge

services: 
    nginx:
        image: nginx:latest
        container_name: webserver
        ports: 
            - "80:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravelnet
        
    mysql:
        image: mysql:5.7.22
        container_name: dblaravel
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./query/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_HOST: "%"
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravelnet
    
    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: apps
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravelnet
